
[workspace]
members = [
    "acts",
    "store/sqlite",
    "store/postgres",
    "plugins/state",
    "examples/plugins/state",
]
exclude = ["examples/**"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.44" }
async-trait = { version = "0.1.88" }
