
[package]
authors = ["Yao <yaojianpin@sohu.com>"]
description = "a fast, tiny, extensiable workflow engine"
edition = "2021"
keywords = ["workflow"]
license = "Apache-2.0"
name = "acts"
homepage = "https://docs.rs/acts"
repository = "https://github.com/yaojianpin/acts.git"
version = "0.10.5"

[dependencies]
async-trait = "0.1.80"
chrono = "0.4.38"
criterion = "0.4.0"
duckdb = { version = "0.10.2", features = ["r2d2"], optional = true }
futures = "0.3.30"
globset = "0.4.14"
hex = { version = "0.4.3", features = ["serde"] }
moka = { version = "0.12.7", features = ["sync"] }
nanoid = "0.4.0"
once_cell = "1.19.0"
r2d2 = { version = "0.8.10", optional = true }
regex = "1.10.4"
rquickjs = { version = "0.6.2", features = ["full", "parallel"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
serde_repr = "0.1.19"
serde_yaml = "0.9.34"
slotmap = "1.0.7"
spin = { version = "0.9.8", default-features = false, features = [
    "mutex",
    "spin_mutex",
] }
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }

[features]
default = []
store = ["duckdb", "r2d2"]
package = []


[[bench]]
harness = false
name = "workflow"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

workspace = { members = ["examples/packet/pack1"] }
