
[workspace]
members = [
    "acts",
    "store/sqlite",
    "store/postgres",
    "plugins/state",
    "examples/plugins/*",
]
exclude = ["examples/plugins/state"]
resolver = "3"


[workspace.dependencies]
tokio = { version = "1.44", features = ["full"] }
async-trait = { version = "0.1.88" }
